[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "zisi"

# Allow iframe embedding inside Plato
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
